/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAusenciasRouteImport } from './routes/app.ausencias'
import { Route as AppCalendarioRouteImport } from './routes/app.calendario'
import { Route as AppComunicacionesRouteImport } from './routes/app.comunicaciones'
import { Route as AppConfiguracionRouteImport } from './routes/app.configuracion'
import { Route as AppDocumentosRouteImport } from './routes/app.documentos'
import { Route as AppEvaluacionesRouteImport } from './routes/app.evaluaciones'
import { Route as AppFichajeRouteImport } from './routes/app.fichaje'
import { Route as AppHorariosRouteImport } from './routes/app.horarios'
import { Route as AppTareasRouteImport } from './routes/app.tareas'
import { Route as AppVacacionesRouteImport } from './routes/app.vacaciones'
import { Route as AppEmpleadosIndexRouteImport } from './routes/app.empleados.index'
import { Route as AppEmpleadosIdRouteImport } from './routes/app.empleados.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAusenciasRoute = AppAusenciasRouteImport.update({
  id: '/ausencias',
  path: '/ausencias',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppComunicacionesRoute = AppComunicacionesRouteImport.update({
  id: '/comunicaciones',
  path: '/comunicaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosRoute = AppDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AppRoute,
} as any)
const AppEvaluacionesRoute = AppEvaluacionesRouteImport.update({
  id: '/evaluaciones',
  path: '/evaluaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppFichajeRoute = AppFichajeRouteImport.update({
  id: '/fichaje',
  path: '/fichaje',
  getParentRoute: () => AppRoute,
} as any)
const AppHorariosRoute = AppHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => AppRoute,
} as any)
const AppTareasRoute = AppTareasRouteImport.update({
  id: '/tareas',
  path: '/tareas',
  getParentRoute: () => AppRoute,
} as any)
const AppVacacionesRoute = AppVacacionesRouteImport.update({
  id: '/vacaciones',
  path: '/vacaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpleadosIndexRoute = AppEmpleadosIndexRouteImport.update({
  id: '/empleados/',
  path: '/empleados/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpleadosIdRoute = AppEmpleadosIdRouteImport.update({
  id: '/empleados/$id',
  path: '/empleados/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/ausencias': typeof AppAusenciasRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/comunicaciones': typeof AppComunicacionesRoute
  '/app/configuracion': typeof AppConfiguracionRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/evaluaciones': typeof AppEvaluacionesRoute
  '/app/fichaje': typeof AppFichajeRoute
  '/app/horarios': typeof AppHorariosRoute
  '/app/tareas': typeof AppTareasRoute
  '/app/vacaciones': typeof AppVacacionesRoute
  '/app/': typeof AppIndexRoute
  '/app/empleados/$id': typeof AppEmpleadosIdRoute
  '/app/empleados/': typeof AppEmpleadosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/ausencias': typeof AppAusenciasRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/comunicaciones': typeof AppComunicacionesRoute
  '/app/configuracion': typeof AppConfiguracionRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/evaluaciones': typeof AppEvaluacionesRoute
  '/app/fichaje': typeof AppFichajeRoute
  '/app/horarios': typeof AppHorariosRoute
  '/app/tareas': typeof AppTareasRoute
  '/app/vacaciones': typeof AppVacacionesRoute
  '/app': typeof AppIndexRoute
  '/app/empleados/$id': typeof AppEmpleadosIdRoute
  '/app/empleados': typeof AppEmpleadosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/ausencias': typeof AppAusenciasRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/comunicaciones': typeof AppComunicacionesRoute
  '/app/configuracion': typeof AppConfiguracionRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/evaluaciones': typeof AppEvaluacionesRoute
  '/app/fichaje': typeof AppFichajeRoute
  '/app/horarios': typeof AppHorariosRoute
  '/app/tareas': typeof AppTareasRoute
  '/app/vacaciones': typeof AppVacacionesRoute
  '/app/': typeof AppIndexRoute
  '/app/empleados/$id': typeof AppEmpleadosIdRoute
  '/app/empleados/': typeof AppEmpleadosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/ausencias'
    | '/app/calendario'
    | '/app/comunicaciones'
    | '/app/configuracion'
    | '/app/documentos'
    | '/app/evaluaciones'
    | '/app/fichaje'
    | '/app/horarios'
    | '/app/tareas'
    | '/app/vacaciones'
    | '/app/'
    | '/app/empleados/$id'
    | '/app/empleados/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/ausencias'
    | '/app/calendario'
    | '/app/comunicaciones'
    | '/app/configuracion'
    | '/app/documentos'
    | '/app/evaluaciones'
    | '/app/fichaje'
    | '/app/horarios'
    | '/app/tareas'
    | '/app/vacaciones'
    | '/app'
    | '/app/empleados/$id'
    | '/app/empleados'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/ausencias'
    | '/app/calendario'
    | '/app/comunicaciones'
    | '/app/configuracion'
    | '/app/documentos'
    | '/app/evaluaciones'
    | '/app/fichaje'
    | '/app/horarios'
    | '/app/tareas'
    | '/app/vacaciones'
    | '/app/'
    | '/app/empleados/$id'
    | '/app/empleados/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ausencias': {
      id: '/app/ausencias'
      path: '/ausencias'
      fullPath: '/app/ausencias'
      preLoaderRoute: typeof AppAusenciasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendario': {
      id: '/app/calendario'
      path: '/calendario'
      fullPath: '/app/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comunicaciones': {
      id: '/app/comunicaciones'
      path: '/comunicaciones'
      fullPath: '/app/comunicaciones'
      preLoaderRoute: typeof AppComunicacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracion': {
      id: '/app/configuracion'
      path: '/configuracion'
      fullPath: '/app/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documentos': {
      id: '/app/documentos'
      path: '/documentos'
      fullPath: '/app/documentos'
      preLoaderRoute: typeof AppDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evaluaciones': {
      id: '/app/evaluaciones'
      path: '/evaluaciones'
      fullPath: '/app/evaluaciones'
      preLoaderRoute: typeof AppEvaluacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fichaje': {
      id: '/app/fichaje'
      path: '/fichaje'
      fullPath: '/app/fichaje'
      preLoaderRoute: typeof AppFichajeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/horarios': {
      id: '/app/horarios'
      path: '/horarios'
      fullPath: '/app/horarios'
      preLoaderRoute: typeof AppHorariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tareas': {
      id: '/app/tareas'
      path: '/tareas'
      fullPath: '/app/tareas'
      preLoaderRoute: typeof AppTareasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vacaciones': {
      id: '/app/vacaciones'
      path: '/vacaciones'
      fullPath: '/app/vacaciones'
      preLoaderRoute: typeof AppVacacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/empleados/': {
      id: '/app/empleados/'
      path: '/empleados'
      fullPath: '/app/empleados/'
      preLoaderRoute: typeof AppEmpleadosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/empleados/$id': {
      id: '/app/empleados/$id'
      path: '/empleados/$id'
      fullPath: '/app/empleados/$id'
      preLoaderRoute: typeof AppEmpleadosIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAusenciasRoute: typeof AppAusenciasRoute
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppComunicacionesRoute: typeof AppComunicacionesRoute
  AppConfiguracionRoute: typeof AppConfiguracionRoute
  AppDocumentosRoute: typeof AppDocumentosRoute
  AppEvaluacionesRoute: typeof AppEvaluacionesRoute
  AppFichajeRoute: typeof AppFichajeRoute
  AppHorariosRoute: typeof AppHorariosRoute
  AppTareasRoute: typeof AppTareasRoute
  AppVacacionesRoute: typeof AppVacacionesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEmpleadosIdRoute: typeof AppEmpleadosIdRoute
  AppEmpleadosIndexRoute: typeof AppEmpleadosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAusenciasRoute: AppAusenciasRoute,
  AppCalendarioRoute: AppCalendarioRoute,
  AppComunicacionesRoute: AppComunicacionesRoute,
  AppConfiguracionRoute: AppConfiguracionRoute,
  AppDocumentosRoute: AppDocumentosRoute,
  AppEvaluacionesRoute: AppEvaluacionesRoute,
  AppFichajeRoute: AppFichajeRoute,
  AppHorariosRoute: AppHorariosRoute,
  AppTareasRoute: AppTareasRoute,
  AppVacacionesRoute: AppVacacionesRoute,
  AppIndexRoute: AppIndexRoute,
  AppEmpleadosIdRoute: AppEmpleadosIdRoute,
  AppEmpleadosIndexRoute: AppEmpleadosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
